export const detectingLogsMock = [
  {
    id: "DL-1001",
    ts: new Date().toISOString(),
    category: "behavior",
    severity: "medium",
    camera: "Camera 1",
    location: "Barn A",
    title: "Abnormal pacing detected",
    message: "Cow #12 shows repeated pacing near the gate for 2.1 minutes.",
  },
  {
    id: "DL-1002",
    ts: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    category: "weather",
    severity: "medium",
    camera: "N/A",
    location: "Farm perimeter",
    title: "Heavy rain alert (D+3)",
    message: "Forecast indicates 60–90mm rainfall with strong wind (18 m/s).",
  },
  {
    id: "DL-1003",
    ts: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    category: "sound",
    severity: "low",
    camera: "Camera 3",
    location: "Barn C",
    title: "Unusual vocalization pattern",
    message: "High-frequency calls detected for 45s near the feeding area.",
  },
  {
    id: "DL-1004",
    ts: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    category: "camera",
    severity: "low",
    camera: "Camera 4",
    location: "External surveillance",
    title: "Camera offline/online flapping",
    message: "Intermittent network stability caused brief disconnects (3x).",
  },
  {
    id: "DL-1005",
    ts: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    category: "behavior",
    severity: "high",
    camera: "Camera 2",
    location: "Barn B",
    title: "Recovered from abnormal lying",
    message: "Cow #7 posture returned to normal after 6 minutes.",
  },
];
